Foxlider/FASTER

FASTER/Models/Converters.cs, FASTER/Models/ServerProfile.cs, FASTER/Views/Profile.xaml
I couldn't re-open the PR you commented on, so I made changes and opened this one. 
The only change I did was to catch that Regex exception and show an error message to the user when they use an invalid expression. Unfortunately, without writing a Regex parser or importing a third party library, there is no convenient way of validating Regex expressions. 
Perhaps the error text and all is a bit overkill, but I was just following what seems to be the standard for Metro-style UI apps.
=> Add filtering/searching to Profile mods

FASTER/App.config, FASTER/Models/ServerProfile.cs, FASTER/Models/SteamUpdaterModel.cs, FASTER/Properties/Settings.Designer.cs, FASTER/Properties/Settings.settings, FASTER/ViewModel/SteamUpdaterViewModel.cs, FASTER/Views/Profile.xaml, FASTER/Views/Updater.xaml
Fixes #70
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [ x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
=> [BUG] DLC is named CLSA instead of CSLA

FASTER/FASTER.csproj, FASTER/ViewModel/SteamUpdaterViewModel.cs, FASTER_Version.xml
=> Feature/update 1.8

.github/workflows/codeql-analysis.yml, FASTER.sln, FASTER/FASTER.csproj, FASTER/ViewModel/SteamUpdaterViewModel.cs, FASTER_Version.xml
=> Fix for the updater to skip unneeded downloads

FASTER/FASTER.csproj, FASTER/ViewModel/SteamUpdaterViewModel.cs
=> I think I finally got that bug

FASTER/FASTER.csproj, FASTER/ViewModel/SteamUpdaterViewModel.cs, FASTER_Version.xml
=> Version bump to 1.9a

.github/workflows/codeql-analysis.yml, FASTER/FASTER.csproj, FASTER/Models/SteamWebApi.cs, FASTER/ViewModel/SteamUpdaterViewModel.cs, FASTERTests/FASTERTests.csproj, FASTER_Version.xml
=> Update 1.9c to fix TryAnotherCM

FASTER/FASTER.csproj, FASTER_Version.xml
=> HOTFIX cuz dotnet 7 fucked up release

FASTER/FASTER.csproj, FASTER_Version.xml
=> It did not work and I will scream

FASTER/App.config, FASTER/FASTER.csproj, FASTER/Models/ServerProfile.cs, FASTER/Models/SteamUpdaterModel.cs, FASTER/Properties/Settings.Designer.cs, FASTER/Properties/Settings.settings, FASTER/ViewModel/ProfileViewModel.cs, FASTER/ViewModel/SteamUpdaterViewModel.cs, FASTER/Views/Profile.xaml, FASTER/Views/Updater.xaml, FASTER_Version.xml
=> Feature/update 1.9

FASTER Maintenance/Models/17Models.cs, FASTER Maintenance/Models/ServerCfg.cs, FASTER/FASTER.csproj, FASTER/Models/ServerCfg.cs, FASTER/Views/Profile.xaml, FASTER_Version.xml
This is still a WIP but it will allow people to have access to:
```
LogObjectNotFound = true;        //
SkipDescriptionParsing = false;   // Bi default Values 
ignoreMissionLoadErrors = false;  //
roleTimeOut = 90;       //
votingTimeOut = 60;     //
briefingTimeOut = 60;   // BI values by default
debriefingTimeOut = 45; //
armaUnitsTimeout = 30;  //
```
You will be able to change the time the same way currently lobby time out is set. I will all go into Server Advanced. I can put it in it's whole own section but it felt like it seemed right their.
#https://github.com/Foxlider/FASTER/issues/91
#https://github.com/Foxlider/FASTER/discussions/124
Still to be tested
=> WIP - Features For Faster

FASTER/Models/Arma3Profile.cs, FASTER/Models/ArmaDeployment.cs, FASTER/Models/ArmaMod.cs, FASTER/Models/ServerCfg.cs, FASTER/Models/ServerProfile.cs, FASTER/Models/SteamUpdaterModel.cs, FASTER/Models/SteamWebApi.cs, FASTER/ViewModel/DeploymentViewModel.cs, FASTER/ViewModel/ModsViewModel.cs, FASTER/ViewModel/ProfileViewModel.cs, FASTER/ViewModel/SteamUpdaterViewModel.cs, FASTER/Views/Deployment.xaml, FASTER/Views/Mods.xaml.cs, FASTER/Views/Profile.xaml, FASTER/Views/ServerStatus.xaml.cs, FASTER/Views/Settings.xaml, FASTER/Views/Settings.xaml.cs, FASTER/Views/Setup.xaml, FASTER/Views/Setup.xaml.cs, FASTER/Views/Updater.xaml
Better readability of code
Not change regarding program. Simple code clean
=> Whitespace Cleanup

FASTER/ViewModel/ProfileViewModel.cs, FASTER/Views/Profile.xaml, FASTER/Views/Profile.xaml.cs
Closes #164 
- Clears confusion for how a mod is loaded on the server
- Updated tool tips
- Updated Column headers to abbreviations
- Launch Faster
- Open Server profile
- Tested on 1.9
=>  [FEAT] Renamed Client/Server headings #165 

FASTER/ViewModel/SteamUpdaterViewModel.cs, README.md
Updates README and Workflow to latest update done in Master
=> [UPDATE] Readme & workflow

FASTER/App.config, FASTER/Models/ServerProfile.cs, FASTER/Models/SteamUpdaterModel.cs, FASTER/Properties/Settings.Designer.cs, FASTER/Properties/Settings.settings, FASTER/ViewModel/ProfileViewModel.cs, FASTER/ViewModel/SteamUpdaterViewModel.cs, FASTER/Views/Profile.xaml, FASTER/Views/Updater.xaml
=> Hotfix for RF Support

.github/workflows/release.yml
Release Generator needed a fix
Shit's broken yo. 
I unbroke it
In progress
=> Fixed Release Generator

.github/workflows/release.yml, FASTER Maintenance/FASTER Maintenance.csproj, FASTER/FASTER - Backup.csproj, FASTER/FASTER.csproj
=> Using `pwsh` for pipeline scripts

.github/workflows/codeql-analysis.yml
=> Sonar Scanner fixes

.github/workflows/release.yml
=> Edit pipeline for Nightly Releases

FASTER/ViewModel/SteamUpdaterViewModel.cs
Login Loop can now been cancelled
Login Loop can now been cancelled
Login Loop is annoying. Now it's annoying but can be cancelled.
Manually
=> Added Cancellation to "Login Loop"

.github/workflows/codeql-analysis.yml, .github/workflows/release.yml
Fixing pipeline logic
Pipelines are a mess. Need to un-mess them
It WILL be
=> Changed pipeline logic
